// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AnimatedImage from "./islands/AnimatedImage.tsx";
import * as $BluredImage from "./islands/BluredImage.tsx";
import * as $OurMission from "./islands/OurMission.tsx";
import * as $ScrollText from "./islands/ScrollText.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AnimatedImage.tsx": $AnimatedImage,
    "./islands/BluredImage.tsx": $BluredImage,
    "./islands/OurMission.tsx": $OurMission,
    "./islands/ScrollText.tsx": $ScrollText,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
